services:
  securion-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: securion-backend
    container_name: securion-backend
    depends_on:
      securion-db:
        condition: service_healthy
        restart: true
      securion-storage:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    networks:
      - securion-backend
      - securion-frontend
    env_file:
      - .env.local
    ports:
      - 5001:5000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${APP_PORT}/health || exit 1",
        ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  securion-backend:
    name: securion-backend
    external: true
  securion-frontend:
    name: securion-frontend
    driver: bridge
