services:
  securion-sphere-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securion-sphere-backend
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - securion-backend
    environment:
      - APP_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - CLIENT_ID
      - CLIENT_SECRET
      - CALLBACK_URL
      - JWT_SECRET
      - JWT_EXPIRE_IN
      - REFRESH_JWT_SECRET
      - REFRESH_JWT_EXPIRE_IN
      - FRONTEND_URL
      - TZ
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  postgres:
    image: postgres
    container_name: securion-pg
    restart: unless-stopped
    volumes:
      - pg_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - securion-backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

networks:
  securion-backend:
    driver: bridge
    name: securion-backend

volumes:
  pg_postgres_data:
    name: pg_postgres_data
    external: true
