services:
  securion-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: securion-backend
    container_name: securion-backend
    depends_on:
      securion-pg:
        condition: service_healthy
        restart: true
      securion-minio:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - securion-backend
      - securion-frontend
    environment:
      - APP_PORT
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - DOCKER_API_HOST
      - DOCKER_API_URL
      - CLIENT_ID
      - CLIENT_SECRET
      - CALLBACK_URL
      - JWT_SECRET
      - JWT_EXPIRE_IN
      - REFRESH_JWT_SECRET
      - REFRESH_JWT_EXPIRE_IN
      - FRONTEND_URL
      - NODE_ENV
      - TZ
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${APP_PORT}/health || exit 1",
        ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  securion-pg:
    image: postgres
    container_name: securion-pg
    restart: unless-stopped
    volumes:
      - securion-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - securion-backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  securion-minio:
    image: quay.io/minio/minio
    container_name: securion-minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - securion-minio-data:/data
    networks:
      - securion-backend
      - securion-frontend
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  securion-backend:
    driver: bridge
    name: securion-backend
  securion-frontend:
    driver: bridge
    name: securion-frontend

volumes:
  securion-pg-data:
    name: securion-pg-data
  securion-minio-data:
    name: securion-minio-data
