name: Deploy dev to Self-Hosted

on:
    workflow_run:
        workflows: ['CI for Development']
        branches: ['dev']
        types:
            - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if previous workflow succeeded
        name: Deploy to dev
        runs-on: self-hosted
        steps:
            - name: Copy repository
              uses: actions/checkout@v3
    
            - name: Build the docker-compose stack
              run: docker compose up -d --build
        
            - name: Clear all docker unused cache
              run: docker system prune -af
